server:
  port: 9002
spring:
  application:
    name: lagou-cloud-gateway
  cloud:
    nacos:
      discovery:
        #配置nacos 多实例集群
        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8080 #sentinel dashboard/console 地址
#        client-ip: 8719 # sentinel会在该端口启动http server，那么这样的话，控制台定义的一些限流等规则才能发送传递过来，
        #如果8719端口被占用，那么会依次+1
    gateway:
      routes: # 路由可以有多个
        - id: service-user-router # 我们⾃定义的路由 ID，保持唯⼀
          #uri: http://127.0.0.1:8092 #目标服务地址 ⾃动投递微服务（部署多实例） 动态路由：uri配置的应该是⼀个服务名称，⽽不应该是⼀个具体的服务实例的地址
          uri: lb://lagou-service-user
          # gateway⽹关从服务注册中⼼获取实例信息然后负载后路由
          predicates: # 断言：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含多种默 认⽅法来将Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
            - Path=/api/user/**
          filters:
              - StripPrefix=1 #去掉api
        - id: service-code-router # 我们⾃定义的路由 ID，保持唯⼀
          #uri: http://127.0.0.1:8081 # ⽬标服务地址
          uri: lb://lagou-service-code
          #http://localhost:9002/resume/openstate/1545132
          #http://127.0.0.1:8081/openstate/1545132
          predicates: # 断言：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含多种默 认⽅法来将Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
            - Path=/api/code/**
          filters:
              - StripPrefix=1 #去掉api
        - id: service-email-router
          uri: lb://lagou-service-email
          predicates:
            - Path=/api/email/**
          filters:
              - StripPrefix=1 #去掉api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接⼝的细节
  endpoint:
    health:
      show-details: always
